const projects = [
  {
    project: "IOD",
    description:
      "สมาคมส่งเสริมสถาบันกรรมการบริษัทไทย (Thai IOD) เป็นองค์กรที่มีบทบาทสำคัญในการพัฒนาความเป็นมืออาชีพของกรรมการ และส่งเสริมให้เกิดการกำกับดูแลกิจการที่ดีในประเทศไทย Thai IOD",
    stack: "Nuxt.js, Nest.js, MySql",
    detail: `<div class="font-semibold"><div><p class="text-gray-800 dark:text-gray-100">- วางแผน Task ร่วมกับคนในทีม</p></div><div><p class="text-gray-800 dark:text-gray-100">- ออกแบบ Database ร่วมกับคนในทีม</p></div><div><p class="text-gray-800 dark:text-gray-100">- ขึ้นโครงสร้าง UI หน้า Frontend</p></div><div><p class="text-gray-800 dark:text-gray-100">- สร้าง Component ที่จำเป็น</p></div><div><p class="text-gray-800 dark:text-gray-100">- Support, Review code และแก้ไขปัญหาต่างๆ</p><p class="text-gray-800 dark:text-gray-100">- ทำ API ต่างๆร่วมกับคนในทีม</p><p class="text-gray-800 dark:text-gray-100">- แก้ bug ต่างๆที่เจอ</p></div></div>`,
    link: "",
    // image: image,
    year: "2024",
  },
  {
    project: "Loco Parking Cloud",
    description: "เป็นระบบจัดการข้อมูลการเข้า-ออกรถของสาขาต่างๆ",
    stack: "Laravel, MySQL",
    detail: `<div class="font-semibold"><div><p class="text-gray-800 dark:text-gray-100">- Refactor code ให้เป็น version ล่าสุด</p><p class="text-gray-800 dark:text-gray-100">- สร้าง crom job ดึงข้อมูลจาก AWS S3</p><p class="text-gray-800 dark:text-gray-100">- สร้าง ETL Function สำหรับ report ต่างๆ</p><p class="text-gray-800 dark:text-gray-100">- สร้าง/ปรับแก้ report ต่างๆ</p><p class="text-gray-800 dark:text-gray-100">- แก้ bug ต่างๆที่เจอ</p></div></div>`,
    link: "",
    // image: image,
    year: "2024",
  },
  {
    project: "E-Office Automation",
    description:
      "เป็นระบบจัดการสำนักงานเศรษฐกิจการเกษตร ซึ่งจะประกอบด้วยระบบย่อยคือ ระบบบริหารเอกสารอิเล็กทรอนิกส์ และระบบสารบรรณอิเล็กทรอนิกส์",
    stack: "Vue.js, Node.js, PostgreSQL",
    detail: `<div class="font-semibold"><div><p class="text-gray-800 dark:text-gray-100">- วางแผน Task ร่วมกับคนในทีม</p></div><div><p class="text-gray-800 dark:text-gray-100">- ออกแบบ Database ร่วมกับคนในทีม</p></div><div><p class="text-gray-800 dark:text-gray-100">- ขึ้นโครงสร้าง UI หน้า Frontend</p></div><div><p class="text-gray-800 dark:text-gray-100">- สร้าง Component ที่จำเป็น</p></div><div><p class="text-gray-800 dark:text-gray-100">- Support, Review code และแก้ไขปัญหาต่างๆ</p></div></div>`,
    link: "",
    // image: image,
    year: "2023",
  },
  {
    project: "XFAS",
    description:
      "ระบบให้บริการข้อมูลดิจิตอลทางอากาศ ที่จะช่วยให้คุณสร้างธุรกิจได้กว้างไกล เเค่ระบุขนาดพื้นที่ วันเวลา และตำแหน่งที่ตั้งของคุณ",
    stack: "Nuxt.js, Laravel, MySQL",
    detail: `<div class="font-semibold"><div><p class="text-gray-800 dark:text-gray-100">- วางแผน Task ให้กับคนในทีม</p></div><div><p class="text-gray-800 dark:text-gray-100">- ขึ้นโครงสร้าง UI หน้า Frontend</p></div><div><p class="text-gray-800 dark:text-gray-100">- จัดทำระบบ Backoffice และ API ต่างๆ</p></div><div><p class="text-gray-800 dark:text-gray-100">- Review code และแก้ไขปัญหาต่างๆ</p></div><div><p class="text-gray-800 dark:text-gray-100">- Deploy</p></div></div>`,
    link: "https://xfas.ksta.co",
    // image: image,
    year: "2023",
  },
  {
    project: "Thai Wara",
    description: `Thai Wara "ยืนหนึ่งในตะวันออกกลาง" พร้อมผลักดันสินค้าไทย ให้กลุ่มประเทศตะวันออกกลาง`,
    stack: "Vue.js",
    detail: `<div class="font-semibold"><div><p class="text-gray-800 dark:text-gray-100">- ขึ้นโครงสร้าง UI หน้า Frontend</p></div><div><p class="text-gray-800 dark:text-gray-100">- สร้าง Component ต่างๆ</p></div></div>`,
    link: "https://thaiwara.ksta.co/login",
    // image: image,
    year: "2023",
  },
  {
    project: "SUT",
    description: "เป็นระบบของหน่วยงาน มหาวิทยาลัยเทคโนโลยีสุรนารี",
    stack: "Vue.js, Laravel, MySQL",
    detail: `<div class="font-semibold"><div><p class="text-gray-800 dark:text-gray-100">- จัดทําหน้าแบบฟอร์มพิจารณา</p></div><div><p class="text-gray-800 dark:text-gray-100">- แผนงานและแบบฟอร์มพิจารณา</p></div><div><p class="text-gray-800 dark:text-gray-100">- Integrate API</p></div><div><p class="text-gray-800 dark:text-gray-100">- Support และแก้ไขปัญหาต่างๆ</p></div></div>`,
    link: "https://sut-web.ksta.co/",
    // image: image,
    year: "2023",
  },
  {
    project: "Bear Wash F-Card",
    description:
      " เป็นระบบจัดการหลังบ้านของ Bear Wash เกี่ยวกับประเภทบัตรต่างๆ และการตั้งค่าโปรโมชั่น รวมถึงการ Topup, Discount, Event และการตรวจสอบยอดเงิน",
    stack: "Laravel, MySQL",
    detail: `<div class="font-semibold"><div><p class="text-gray-800 dark:text-gray-100">- ปรับ Database ให้เหมาะสมกับระบบ</p></div><div><p class="text-gray-800 dark:text-gray-100">- เพิ่มหน้าจัดการ Topup Promotion</p></div><div><p class="text-gray-800 dark:text-gray-100">- เพิ่มหน้าจัดการ Discount Promotion</p></div><div><p class="text-gray-800 dark:text-gray-100">- เพิ่มหน้าจัดการ Event Promotion</p></div><div><p class="text-gray-800 dark:text-gray-100">- เพิ่มหน้าจัดการประเภทบัตร</p></div><div><p class="text-gray-800 dark:text-gray-100">- เพิ่มหน้าจัดการบัตร</p></div><div><p class="text-gray-800 dark:text-gray-100">- เพิ่มหน้า Log Activity</p></div><div><p class="text-gray-800 dark:text-gray-100">- Support และแก้ไขปัญหาต่างๆ</p></div></div>`,
    link: "",
    // image: image,
    year: "2023",
  },
  {
    project: "นิทรารมณ์",
    description:
      "เป็น Application ช่วยจัดการการนอนหลับ ที่สามารถวิเคราะห์ผลการเปรียบเทียบการนอนของผู้ใช้ย้อนหลัง 7 วัน และยังมีการให้คำแนะนำเกี่ยวกับการนอนของผู้ใช้งาน",
    stack: "SwiftUi, Laravel, Vue.js, MySQL",
    detail: `<div class="font-semibold"><div><p class="text-gray-800 dark:text-gray-100">- จัดทําในส่วนของ iOS หน้า login with social (Facebook/Google)</p></div><div><p class="text-gray-800 dark:text-gray-100">- จัดทำระบบ Backoffice และ API ต่างๆ</p></div><div><p class="text-gray-800 dark:text-gray-100">- จัดทำหน้า Register view</p></div><div><p class="text-gray-800 dark:text-gray-100">- Support และแก้ไขปัญหาต่างๆ</p></div></div>`,
    link: "",
    // image: image,
    year: "2022",
  },
  {
    project: "ระบบ Franchise Portal",
    description:
      "เป็นระบบของ โครงการ PTTOR(Cafe Amazon) ที่สามารถการจัดการข้อมูลร้านค้า, จัดการผู้บริหาร, จัดการข้อมูลพนักงาน, การสั่งซื้อ(E-Order), หลักสูตร, ข่าวสารและบทความต่างๆ และอื่นๆ",
    stack: "Vue.js, MySQL",
    detail: `<div class="font-semibold"><div><p class="text-gray-800 dark:text-gray-100">- จัดทําในส่วนของ Frontend ในเมนูที่ได้รับมอบหมายและแก้ไขปัญหาที่พบ</p></div><div><p class="text-gray-800 dark:text-gray-100">- Deploy ขึ้นระบบ Salesforce</p></div></div>`,
    link: "https://pttororg1--devpro1.sandbox.my.site.com/FranchisePortal2/FranchisePortalLogin",
    // image: image,
    year: "2022",
  },
  {
    project: "AEON METAVERSE Virtual Party 2022",
    description:
      "เป็นกิจกรรมที่ทาง AEON จัดขึ้นตอนขึ้นปีใหม่ โดยจะให้ทำกิจกรรมสั้นๆขึ้นมา คือ การแข่งขันเล่นเกมบน เว็บไซต์ ในเว็บจะสามารถแต่งตัวละครของแต่ละคนได้ และจะแบบการเเข่งขั้นออกเป็นกลุ่มสีต่างๆ เกมจะเป็นเกมในรูปแบบคล้ายๆ Cookie run และในเว็บไซต์จะแสดงตาราง Ranking คะแนน รายบุคคลหรือตามกลุ่มสีได้",
    stack: "Laravel, MySQL",
    detail: `<div class="font-semibold"><div><p class="text-gray-800 dark:text-gray-100">- จัดทําในส่วน Frontend หน้าโปรไฟล์</p></div><div><p class="text-gray-800 dark:text-gray-100">- Ranking board</p></div><div><p class="text-gray-800 dark:text-gray-100">- Integrate API ที่เกี่ยวข้องกับหน้าโปรไฟล์หรือ Ranking board</p></div><div><p class="text-gray-800 dark:text-gray-100">- Deploy</p></div></div>`,
    link: "",
    // image: image,
    year: "2022",
  },
  {
    project: "Thai Trade USA",
    description:
      "เป็นระบบแสดงข้อมูล Event หรือ ข่าวสารต่างๆ ของ The Department of International Trade Promotion",
    stack: "Vue.js, Laravel, MySQL",
    detail: `<div class="font-semibold"><div><p class="text-gray-800 dark:text-gray-100">- ออกแบบ Database</p></div><div><p class="text-gray-800 dark:text-gray-100">- Frontend</p></div><div><p class="text-gray-800 dark:text-gray-100">- Backoffice</p></div><div><p class="text-gray-800 dark:text-gray-100">- Backend</p></div><div><p class="text-gray-800 dark:text-gray-100">- Deploy</p></div></div>`,
    link: "https://thaitradeusa.com/",
    // image: image,
    year: "2022",
  },
  {
    project: "Powerpod Fitness Club",
    description:
      "เป็นเว็บไซต์ที่จะวิเคราะห์ผลการวัดผลทางกายภาพของลูกค้า และแสดงออกมาเป็น Report ทำให้กับทาง Powerpod Fitness Club เป็นโรงยิมสำหรับผู้สูงอายุ คนป่วย และคนอ้วน ในสังคมญี่ปุ่น",
    stack: "Vue.js, Laravel, MySQL",
    detail: `<div class="font-semibold"><div><p class="text-gray-800 dark:text-gray-100">- ออกแบบ Database</p></div><div><p class="text-gray-800 dark:text-gray-100">- Frontend</p></div><div><p class="text-gray-800 dark:text-gray-100">- Backoffice</p></div><div><p class="text-gray-800 dark:text-gray-100">- Backend</p></div><div><p class="text-gray-800 dark:text-gray-100">- Deploy</p></div></div>`,
    link: "https://powerpodfitness.ksta.co/login",
    // image: image,
    year: "2022",
  },
  {
    project: "PMUC MediPod System",
    description: "",
    stack: "Laravel, MySQL",
    detail: `<div class="font-semibold"><div><p class="text-gray-800 dark:text-gray-100">- จัดทําในส่วน Frontend หน้าจัดการ Meeting (CRUD)</p></div><div><p class="text-gray-800 dark:text-gray-100">- จัดการหน้า Calendar</p></div><div><p class="text-gray-800 dark:text-gray-100">- Integrate API ที่เกี่ยวข้อง</p></div></div>`,
    link: "https://pmuc.ksta.co/user/login",
    // image: image,
    year: "2022",
  },
  {
    project: "OSCC Consulting",
    description:
      "ระบบให้คำปรึกษาและพัฒนาผู้ปฏิบัติงานคุ้มครองเด็กและผู้ถูกกระทำด้วยความรุนแรงใรครอบครัว",
    stack: "Vue.js, Laravel, Pusher, MySQL",
    detail: `<div class="font-semibold"><div><p class="text-gray-800 dark:text-gray-100">- รับผิดชอบด้าน API ด้วย Laravel</p></div><div><p class="text-gray-800 dark:text-gray-100">- จัดทําในส่วน Login, Chat, ฟอร์มสร้างเคสต่างๆของระบบ</p></div><div><p class="text-gray-800 dark:text-gray-100">- Integrate API ที่เกี่ยวข้อง</p></div><div><p class="text-gray-800 dark:text-gray-100">- แก้ไขปัญหาที่พบ</p></div></div>`,
    link: "https://oscc.consulting/",
    // image: image,
    year: "2022",
  },
  {
    project: "TN Logistic System (Driver phase 2)",
    description:
      "เป็นระบบจัดการ การรับส่งตู้คอนเทรนเนอร์ ไปยังปลายทาง โดยจะมีขั้นตอนการทำงานต่างๆ ตั้งแต่ สร้าง Order เลือก Carrier, รถ, คนขับ จนไปถึงการออกใบวางบิลที่ Export ออกมาเป็น PDF file พร้อมระบบส่ง Email ไปยังผู้ให้บริการที่ได้เลือกไว้ เพื่อแจ้งเตือนตามขั้นตอนต่างๆ ของระบบ ทำให้กับหน่วยงานเอกชน",
    stack: "Vue.js, Laravel, MySQL",
    detail: `<div class="font-semibold"><div><p class="text-gray-800 dark:text-gray-100">- ออกแบบ Database</p></div><div><p class="text-gray-800 dark:text-gray-100">- Frontend</p></div><div><p class="text-gray-800 dark:text-gray-100">- Backend</p></div><div><p class="text-gray-800 dark:text-gray-100">- Deploy</p></div></div>`,
    link: "",
    // image: image,
    year: "2022",
  },
  {
    project: "Gosure Online",
    description: " เป็นระบบซื้อประกันรถยนต์ออนไลน์",
    stack: "Vue.js, Laravel, MySQL",
    detail: `<div class="font-semibold"><div><p class="text-gray-800 dark:text-gray-100">- จัดทําในส่วน Front-end หน้า Landing page</p></div><div><p class="text-gray-800 dark:text-gray-100">- หน้ารายการหรือรายละเอียดบทความ</p></div><div><p class="text-gray-800 dark:text-gray-100">- Integrate API ที่เกี่ยวข้อง</p></div></div>`,
    link: "",
    // image: image,
    year: "2021",
  },
  {
    project: "ASB Marketing System",
    description: "เป็นระบบจัดการเช่าพื้นที่ในการขายของ",
    stack: "Laravel, MySQL",
    detail: `<div class="font-semibold"><div><p class="text-gray-800 dark:text-gray-100">- จัดทําในส่วน หน้า Login</p></div><div><p class="text-gray-800 dark:text-gray-100">- หน้ารายการเมนูต่างๆ</p></div><div><p class="text-gray-800 dark:text-gray-100">- หน้าจัดการและค้นหาสมาชิก</p></div><div><p class="text-gray-800 dark:text-gray-100">- Integrate API ที่เกี่ยวข้อง</p></div></div>`,
    link: "",
    // image: image,
    year: "2021",
  },
  {
    project: "Biodiversity Big data",
    description:
      "เว็บไซต์แสดงข้อมูลทรัพยากรชีวภาพจากฐานข้อมูล ThaiBiodiversity / ข้อมูลทรัพยากรชีวภาพที่มีศักยภาพทางเศรษฐกิจ ของทางสํานักงานพัฒนาเศรษฐกิจจากฐานชีวภาพ(BEDO)",
    stack: "Vue.js, Laravel, MySQL",
    detail: `<div class="font-semibold"><div><p class="text-gray-800 dark:text-gray-100">- จัดทําในส่วนหน้า Landing page</p></div><div><p class="text-gray-800 dark:text-gray-100">- หน้าแสดงรายละเอียดข้อมูลทรัพยากรชีวภาพ</p></div><div><p class="text-gray-800 dark:text-gray-100">- Integrate API ที่เกี่ยวข้อง</p></div></div>`,
    link: "https://www.nbbch.org/",
    // image: image,
    year: "2021",
  },
  {
    project: "MVTV Authen Streaming",
    description: "",
    stack: "Laravel, MySQL",
    detail: `<div class="font-semibold"><p class="text-gray-800 dark:text-gray-100">- จัดทํา CRUD ของเมนู Partner management</p></div>`,
    link: "",
    // image: image,
    year: "2021",
  },
  {
    project: "Consmix Sales",
    description: "",
    stack: "Laravel, MySQL",
    detail: `<div class="font-semibold"><p class="text-gray-800 dark:text-gray-100">- สร้างฟังก์ชั่นออกใบคํา สั่งซื้อ Order และ Export ออกมาเป็น PDF filee</p></div>`,
    link: "",
    // image: image,
    year: "2020",
  },
  {
    project: "TN Logistic System",
    description:
      "เป็นระบบจัดการ การรับส่งตู้คอนเทรนเนอร์ ไปยังปลายทาง โดยจะมีขั้นตอนการทำงานต่างๆ ตั้งแต่ สร้าง Order เลือก Carrier, รถ, คนขับ จนไปถึงการออกใบวางบิลที่ Export ออกมาเป็น PDF file พร้อมระบบส่ง Email ไปยังผู้ให้บริการที่ได้เลือกไว้ เพื่อแจ้งเตือนตามขั้นตอนต่างๆ ของระบบ ทำให้กับหน่วยงานเอกชน",
    stack: "Vue.js, Laravel, MySQL",
    detail: `<div class="font-semibold"><div><p class="text-gray-800 dark:text-gray-100">- ออกแบบ Database</p></div><div><p class="text-gray-800 dark:text-gray-100">- Frontend</p></div><div><p class="text-gray-800 dark:text-gray-100">- Backend</p></div><div><p class="text-gray-800 dark:text-gray-100">- Deploy</p></div></div>`,
    link: "https://tnlogistic.ksta.co/login",
    // image: image,
    year: "2020",
  },
  {
    project: "TCDC Connect by CEA",
    description:
      "เป็นเว็บไซต์ที่รวบรวมรายชื่อนักออกแบบในไทยและผลงานต่างๆของพวกเขา จัดทำให้กับทาง CONNECT by CEA ที่เป็นส่วนหนึ่งในงานบริการภาคธุรกิจและการออกแบบของสำนักงานส่งเสริมเศรษฐกิจสร้างสรรค์(สศส.)",
    stack: "Vue.js, Laravel, MySQL",
    detail: `<div class="font-semibold"><div><p class="text-gray-800 dark:text-gray-100">- ออกแบบ Database</p></div><div><p class="text-gray-800 dark:text-gray-100">- Frontend</p></div><div><p class="text-gray-800 dark:text-gray-100">- Backoffice</p></div><div><p class="text-gray-800 dark:text-gray-100">- Backend</p></div><div><p class="text-gray-800 dark:text-gray-100">- Facebook API</p></div><div><p class="text-gray-800 dark:text-gray-100">- Deploy</p></div></div>`,
    link: "https://connect.cea.or.th/",
    // image: image,
    year: "2020",
  },
  {
    project: "ระบบจัดการโครงการวิจัยกรมแพทย์ทหารบก(irbrta)",
    description:
      "เป็นระบบจัดทำโครงการวิจัยต่างๆ ภายในหน่วยงาน ของทาง สำนักงานพิจารณาโครงการวิจัย กรมแพทย์ทหารบก",
    stack: "Vue.js, Laravel, MySQL",
    detail: `<div class="font-semibold"><div><p class="text-gray-800 dark:text-gray-100">- ออกแบบ Database</p></div><div><div><p class="text-gray-800 dark:text-gray-100">- Frontend</p></div><div><p class="text-gray-800 dark:text-gray-100">- Backoffice</p></div><div><p class="text-gray-800 dark:text-gray-100">- Backend</p></div></div></div>`,
    link: "https://irbrta-research.com/",
    // image: image,
    year: "2020",
  },
  {
    project: "ระบบฐานข้อมูลกลางคุณลักษณะเฉพาะสิ่งสิ่อุปกรณ์สายแพทย์",
    description:
      "เป็นระบบค้นหาข้อมูลกลางคุณลักษณะเฉพาะสิ่งอุปกรณ์สายแพทย์ และ Export ใบสั่งพิมพ์ของอุปกรณ์สายแพทย์ออกมาเป็น PDF file ของทาง กรมแพทย์ทหารบก",
    stack: "Vue.js, Laravel, MySQL",
    detail: `<div class="font-semibold"><div><p class="text-gray-800 dark:text-gray-100">- ออกแบบ Database</p></div><div><p class="text-gray-800 dark:text-gray-100">- Frontend</p></div><div><p class="text-gray-800 dark:text-gray-100">- Backoffice</p></div><div><p class="text-gray-800 dark:text-gray-100">- Backend</p></div><div><p class="text-gray-800 dark:text-gray-100">- Deploy</p></div></div>`,
    link: "https://rtamed.com/",
    // image: image,
    year: "2020",
  },
  {
    project: "ระบบรายงานผู้บาดเจ็บหรือเสียชีวิตจากการตกน้ำ จมน้ำ",
    description:
      "เป็นระบบจัดการรายงานผู้บาดเจ็บหรือเสียชีวิตจากการตกน้ำ จมน้ำ ทำให้กับ กองป้องกันการบาดเจ็บ กรมควบคุมโรค กระทรวงสาธารณสุข",
    stack: "Vue.js, Laravel, MySQL",
    detail: `<div class="font-semibold"><div><p class="text-gray-800 dark:text-gray-100">- จัดทํา และแก้ไขในส่วนของ ฟอร์มการกรอกข้อมูล หน้าแสดงรายการผู้บาดเจ็บ หรือเสียชีวิตจากการตกน้ํา</p></div><div><p class="text-gray-800 dark:text-gray-100">- ทํา API บันทึกฟอร์มข้อมูลและดึงข้อมูลรายการ</p></div></div>`,
    link: "https://dip.ddc.moph.go.th/satdrowning/#/login",
    // image: image,
    year: "2020",
  },
];

export default projects;
